# Generated by Django 5.2.1 on 2025-05-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
