// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdntjhjjdbrfgeammizb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbnRqaGpqZGJyZmdlYW1taXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTg1MjIsImV4cCI6MjA2MjI5NDUyMn0.lqZkNbHhBss9NWohXZ8CuUD3eGDQLfKY4GSeakFTa_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);